# Generated by Django 3.2.8 on 2021-10-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='facebook',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='twitter',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='wikipedia',
            field=models.URLField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='instagram',
            field=models.URLField(blank=True, max_length=100),
        ),
    ]
